### ISSUE TITLE
レポジトリの Rename と Transfer を行う

### ISSUE THREAD

**Issue by takano32** [arakawatomonori/covid19-surveryor#57]
Rename と Transfer を行う十分な理由が増えてきた。

Transfer 先候補

https://github.com/arakawatomonori

<img width="637" alt="スクリーンショット 2020-04-17 2 47 56" src="https://user-images.githubusercontent.com/16088/79489267-fd643600-8055-11ea-9cb0-fae22785d2fa.png">

**Comment by takano32** [comment]
名前候補

vscovid-serveyor

**Comment by MaySoMusician** [comment]
Googleがserveyorはsurveyorだと訂正してくるのですが真相は如何ほどでしょうか

**Comment by takano32** [comment]
う。正解は CM のあと・・・

じゃなくて

`vscovid-surveyor` が正しいです。

**Comment by takano32** [comment]
Rename + Transfer できました。

From: https://github.com/yuiseki/vscovid-crawler/

To: https://github.com/arakawatomonori/covid19-surveryor/
