### ISSUE TITLE
実行時のみに実行されるべきコードがsourceの際に実行されないようにする

### ISSUE THREAD

**Issue by 515hikaru** [arakawatomonori/covid19-surveryor#65]
Python でいう `if __name__ == '__main__'` のような構文をを加えたい。

- テストを実行する際に、テストする関数を読み込むために現在 `. ./crawler/wget.sh` などで読み込んでいる
    - この読み込みは関数以外も読み込んでしまう（実行がされる）
- テストしたい関数以外も実行され、環境変数などが整備されないまま実行されてしまいエラーになる
    - 具体的には、現在の `slack-bot/url-map.sh` の下記のコードがテスト時にも実行されている
```bash
channels_id=`get_channels_id`
members_list=`get_members_list $channels_id`

echo members num ${#members_list[@]}

for member in $members_list; do
	member_id=${member:1:-1}
	send_message $member_id
done
```

これを

```bash
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    # ... 実行コマンド
fi
```

などとすればスクリプトとして実行されたときのみ実行され、source されたときには実行されない。はず。（未確認）

参考: https://stackoverflow.com/questions/29966449/what-is-the-bash-equivalent-to-pythons-if-name-main

**Comment by takano32** [comment]
see also. https://rcmdnk.com/blog/2015/07/24/computer-bash-zsh/

**Comment by takano32** [comment]
<img width="260" alt="スクリーンショット 2020-04-17 14 10 29" src="https://user-images.githubusercontent.com/16088/79534359-47c8cf80-80b5-11ea-9917-430ab4832252.png">

**Comment by 515hikaru** [comment]
とりあえずテスト対象になっている wget.sh と url-map.sh についてやります。
