### ISSUE TITLE
リリース時にCloudFrontのキャッシュを削除する

### ISSUE THREAD

**Issue by halsk** [arakawatomonori/covid19-surveryor#67]
とりあえず CloudFront の Invalidate 権限を持つ IAM ユーザーを作りました。
今は deploy には CircleCI を使っているんですかね。
どのように deploy されているのかよくわからないのですが、どうするのが良いでしょうか。
aws CLI を CircleCI の VM から実行できれば、シェルスクリプト作って Makefile から実行すれば良さそうですが。

**Comment by yuiseki** [comment]
サーバー上で `make publish` というコマンドを実行したときに index.html が更新されるんですが、そのタイミングで invalidate したいです。

> シェルスクリプト作って Makefile から実行すれば良さそう

これでいける気がするので、 aws-cli について調べてみます

**Comment by yuiseki** [comment]
`aws cloudfront create-invalidation --distribution-id XXXXXXXXXXXXXX --paths '/*'`
これだけでいいっぽい？

**Comment by yuiseki** [comment]
https://qiita.com/yamamoto_y/items/cddba970ba0785b98461

**Comment by halsk** [comment]
うん。ただ、 aws cli 自体がインストールされている必要があります。
Circle CI で毎回インストールするのは嫌ですよね。

**Comment by halsk** [comment]
https://circleci.com/orbs/registry/orb/circleci/aws-cli
こういうのがあるね

**Comment by halsk** [comment]
ちょっと私が時間無いので、@yuiseki に KEY/SECRET/distribution-id をお伝えしておきます
